# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    # Lane for Firebase
    desc "Upload to Firebase App Distribution"
    lane :release do
        firebase_app_distribution(
            service_credentials_file: "service-account.json",
            app: ENV["FIREBASE_APP_ID"],
            apk_path: "app/build/outputs/apk/release/app-release.apk",
            testers: "mihirniyogi942@gmail.com",
            release_notes: "Updated app title"
        )
    end
end
