name: Android

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Decode keystore
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks

      # 3. Set env variables
      - name: Set env variables
        run: |
          echo "KEYSTORE_PATH=$(pwd)/app/keystore.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{  secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "QUOTE_API_KEY=${{ secrets.QUOTE_API_KEY }}" > .env

      # 4. Setup jdk
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # 5. Build APK
      - name: Build Signed APK
        run: ./gradlew clean assembleRelease

######     Optional     #####
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: release
#          path: app/build/outputs/apk/release/app-release.apk

      # 6. Decode Firebase Credentials
      - name: Decode Firebase Credentials
        run: echo "${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}" | base64 -d > service-account.json # used by fastlane

      # 7. Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      # 8. Install Ruby Dependencies
      - name: Install Ruby Dependencies
        run: bundle install

      # 9. Upload to Firebase via Fastlane
      - name: Fastlane
        run: bundle exec fastlane release